tail -n +2 ABANDON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ABBREVIATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ABOUT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ABOVE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACCEPT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACCIDENTAL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACCIDENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACCOUNTING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACID_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACROSS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACTIVE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ACTIVITY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADDICTION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADDRESS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADJACENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADMIRE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADMIT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADVENTURE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADVERTISE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADVISE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ADVOCACY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AESTHETICS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AFFILIATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AFGHANISTAN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AFRAID_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AFRICA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AFTERNOON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AFTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AGAINST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AGAIN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AGGRESSIVE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AGREE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AHEAD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AID_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AIRPLANE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AIRPORT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALARM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALLERGY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALLOW_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALMOST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALONE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALSO_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALTOGETHER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ALWAYS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AMBULANCE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AMERICA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANGRY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANIMAL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANIMATION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANNOUNCEMENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANNOYED_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANNUAL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANOINT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANONYMOUS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANOTHER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANSWER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANYTHING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANYTIME_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ANY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APART_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APOLOGIZE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APPEARANCE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APPEAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APPLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APPOINTMENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APPROACH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APPROPRIATION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 APPROVAL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARBITRATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARGUMENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARMADILLO_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARMY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AROUND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARREST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARRIVE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARROGANT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARTICLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ARTWORK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ART_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ASK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ASSOCIATION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ASTHMA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ATHLETE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ATTACK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ATTENTION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ATTITUDE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ATTRACTIVE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUCTION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUDIOLOGY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUNT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUSSIE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUSTRALIA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUSTRIAN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUSTRIA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUTHOR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AUTOMATIC_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AVERAGE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AVOID_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AWARD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AWAY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AWESTRUCK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AWE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AWFUL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 AWKWARD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BABY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BACKSTROKE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BACKWARD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BACON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BAD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BAGEL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BAHRAIN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BALD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BALLOON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BALL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BANANA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BARK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BASEBALL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BASEMENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BASIC_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BASKETBALL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BASKING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BATH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BATTERY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEACH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEAT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEAUTIFUL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BECAUSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BECOME_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEDROOM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BED_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEFORE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEG_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEHIND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BELIEF_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BELOW_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BELT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BENEFIT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BEST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BETTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BETWEEN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BIBLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BICYCLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BID_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BIG_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BINOCULAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BIRTHDATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BIRTHDAY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BIRTHMARK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BITE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BITTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLACK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLAME_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLAND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLEMISH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLESS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLIND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLONDE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLOOD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLOWER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLUE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BLUR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOAT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BODY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOGUS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOLIVIA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOMB_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOOKCASE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOOKCOVER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOOK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BORING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BORN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BORROW_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOSSY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOSS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOTHER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOTH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOTTLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOTTOM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOUNCE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOWL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOXING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOYFRIEND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BOY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRAG_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRAID_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRAILLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRAINSTORM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRAINWASH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRAVE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BREADTH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BREAD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BREAKFAST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BREAK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BREASTFEEDING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BREASTSTROKE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BREATHE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRIEF_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRIGHT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRILLIANT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BROADCAST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BROKE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BROTHER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BROWNNOSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BROWN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRUISE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BRUSH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUDDHISM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUDGET_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUG_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUILD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BULL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BURQA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUSINESS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUSY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUTTERFLY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUTTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUTTON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BUY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 BYE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAKE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CALCULATOR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CALGARY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CALL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CALM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAMERA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAMP_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CANADA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CANCEL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CANCER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CANDLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CANDY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CANNOT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAPITALISM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAPTURE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAREFUL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CARE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CARJACKING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CARRY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CASTE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CATALOGUE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CATCALL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CATCH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CATHOLIC_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CATTLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CAUSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CELEBRATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CENTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CERTIFICATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHAIN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHAIRPERSON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHAIR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHALLENGE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHAMPAGNE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHAMPION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHANCE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHANGE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHAOS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHARACTERISTIC_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHARACTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHARGE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHASE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHATTY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHAT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHEAP_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHEAT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHECKOUT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHECK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHEERLEADING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHEESE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHEETAH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHERRY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHEW_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHICKEN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHILDREN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHINA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHOCOLATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHOICE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHRISTMAS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHRIST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHUBBY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CHURCH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CIGARETTE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CIGAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CIRCLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CITIES_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLAM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLASS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLEANSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLEAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLICKBAIT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLICK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLIMB_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLOAK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLOSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLOTHE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLOUD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CLOWN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COAT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COCAINE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COFFEE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COLD_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COLLEGE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COLORFUL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COLOR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMBINE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMB_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COME_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMFORTABLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMANDO_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMAND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMITMENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMITTEE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMUNICATION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMUNISM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMMUNITY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPANY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPETE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPLAIN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPLETE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPLEX_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPLICATED_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPOSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COMPUTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONCEITED_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONCEPT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONCERN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONDITION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONDOM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONFESS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONFIDENCE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONFIDENTIAL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONFLICT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONFUSED_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONGRATULATION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONGRESS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONNECT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONSCIOUS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONSIDER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONSTITUTION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONSTRUCTION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONTINENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONTINUE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONTRACT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 CONTROL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COOKIE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COOK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COOL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COOPERATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COOPERATIVE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COORDINATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COPYCAT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COPYEDITING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COPYRIGHT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COPYWRITING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COUGH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COUNTRY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COUNT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COURAGE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COURSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COURT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COUSIN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COVER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 COVET_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DATE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DESIGN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DETAIN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DIRECTORS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DISABILITIES_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DISCOLOR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DOWN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 DUB_Transcription_Pose.csv >> all_pose.csv
tail -n +2 EDUCATION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ELSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 EMERGENCY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ENGINEERING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 EVERYBODY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 EXCLAIM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 EYE-CATCHING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FIZZ_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FLAMES_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FLICKER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FLU_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FORERUNNER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FORTH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FRACTURE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 FROTH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 GENTLEMAN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 GERMANY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 GNAW_Transcription_Pose.csv >> all_pose.csv
tail -n +2 GULP_Transcription_Pose.csv >> all_pose.csv
tail -n +2 HANDSPEAK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 HARVEST_Transcription_Pose.csv >> all_pose.csv
tail -n +2 HEADWEAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 HEAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 HERE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 HITHERTO_Transcription_Pose.csv >> all_pose.csv
tail -n +2 IMPAIRED_Transcription_Pose.csv >> all_pose.csv
tail -n +2 INSERT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 INSURANCE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 INTROSPECT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 INVOICE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 IN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 JULIENNE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 LAURENT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 LEAN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 LESS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 LIFE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 LIGHTS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 Language_Transcription_Pose.csv >> all_pose.csv
tail -n +2 MARK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 MEDIAN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 MOLLYCODDLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 NEPAL_Transcription_Pose.csv >> all_pose.csv
tail -n +2 NOW_Transcription_Pose.csv >> all_pose.csv
tail -n +2 OCEANIA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 OFFSPRING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 OSAMA_Transcription_Pose.csv >> all_pose.csv
tail -n +2 OUT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PAUSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PETITION_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PHONEME_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PHOTOCOPY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PLUS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PREPERATORY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PRIVILEGE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PRIZE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 PURCHASE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 RACING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 RACISM_Transcription_Pose.csv >> all_pose.csv
tail -n +2 RADAR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 REAR-FACING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 REBOUND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 REGARDING_Transcription_Pose.csv >> all_pose.csv
tail -n +2 REVERE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 RIGHT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 ROTE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SCIENCE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SEIZE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SENSE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SERENE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SO-LONG_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SPINE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 STILLBORN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 STUFF_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SURROUND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SWITZERLAND_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SYLLABLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SYRUP_Transcription_Pose.csv >> all_pose.csv
tail -n +2 SYSTEMS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 TACTIC_Transcription_Pose.csv >> all_pose.csv
tail -n +2 THERE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 THROMBUS_Transcription_Pose.csv >> all_pose.csv
tail -n +2 TOPPLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 TOTALITARIAN_Transcription_Pose.csv >> all_pose.csv
tail -n +2 TRIWEEKLY_Transcription_Pose.csv >> all_pose.csv
tail -n +2 TUMOR_Transcription_Pose.csv >> all_pose.csv
tail -n +2 TWEAK_Transcription_Pose.csv >> all_pose.csv
tail -n +2 TWITTER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 UNCOMMON_Transcription_Pose.csv >> all_pose.csv
tail -n +2 UPROOT_Transcription_Pose.csv >> all_pose.csv
tail -n +2 UP_Transcription_Pose.csv >> all_pose.csv
tail -n +2 VANQUISH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 VERITABLE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 WHITE_Transcription_Pose.csv >> all_pose.csv
tail -n +2 WITH_Transcription_Pose.csv >> all_pose.csv
tail -n +2 YONDER_Transcription_Pose.csv >> all_pose.csv
tail -n +2 hello_Transcription_Pose.csv >> all_pose.csv
